server:
  port: 9070
  servlet:
    context-path: /resources
spring:
  application:
    name: resource
  datasource:
    url: jdbc:mysql://112.74.57.253:3306/iam
    username: root
    password: 594682797
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
      defaultZone: http://112.74.57.253:8000/eureka/
security:
  oauth2:
    resource:
      user-info-uri:  http://localhost:9060/user
      prefer-token-info: false